### ISSUE TITLE
Unknow Device

### ISSUE THREAD

**Issue by lillogoal** [DJI-Mobile-SDK-Tutorials/Android-FPVDemo#16] opened 2016-11-23 20:15 UTC
sometimes when i launch my app after check SDK.
it try to find my osmo camera, but sdk return me an unknow device (wifi connection)

**Comment by lillogoal** [comment] 2016-11-23 21:51
ANDROID STUDIO: 2.2.2
MIN SDK: 4.4.1
DEVICE MOTO G3 (2016)
ANDROID VERSION: 6.0.1

THIS IS LOGCAT: 11-23 21:25:59.496 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: Camera needCreateNew: false
11-23 21:25:59.496 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: Gimbal needCreateNew: false
11-23 21:25:59.499 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: FlightController needCreateNew: false
11-23 21:25:59.499 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: oldComponent: dji.sdk.flightcontroller.a@6f43b86
11-23 21:25:59.500 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: update battery platformType: Unknown
11-23 21:25:59.500 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: Battery needCreateNew: false
11-23 21:25:59.500 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: HandHeldController needCreateNew: false
11-23 21:25:59.500 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: RemoteController needCreateNew: false
11-23 21:25:59.500 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: MOBILE_REMOTE_CONTROLLER needCreateNew: false
11-23 21:26:01.431 23837-23884/com.wesii.wesiiplay E/wm220: ****resetSwitchFromWifiFlag
11-23 21:26:01.842 23837-23954/com.wesii.wesiiplay E/c: udt 连接建立 ip:192.168.1.3port:9000
11-23 21:26:02.356 23837-24453/com.wesii.wesiiplay E/UDT-JNI: Connection was broken.
11-23 21:26:02.357 23837-24453/com.wesii.wesiiplay E/c: udt 连接断开 recvLen=-2 ip:192.168.1.3port:9000

**Comment by oliverou** [comment] 2016-11-24 03:55
Hi @lillogoal, thanks for your feedback! We will investigate this issue and fix it in the future SDK version.

**Comment by lillogoal** [comment] 2016-11-24 07:54
ok you, but I noticed that with the official app dji go. how is it that with the official app works well? the Chamber (osmo) is detected and the connection goes perfectly. How Can i do ? @oliverou

**Comment by oliverou** [comment] 2016-11-24 08:07
Hi @lillogoal, which Android SDK version you are using? Android SDK 3.4.1? Could you help to check if you open DJI Go and the Sample App on your mobile device at the same time? Please make sure DJI Go app is stopped running in the background when you run the Sample App.

**Comment by lillogoal** [comment] 2016-11-24 08:49
@oliverou  here my answer.

DJI SDK Is 3.4.1 YES.
THIS IS MY GRADLE:
`ndroid {
    compileSdkVersion 25
    buildToolsVersion "24.0.2"
    defaultConfig {
        applicationId "com.wesii.wesiiplay"
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 1
        multiDexEnabled true

        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}`


I also tried to compile with android sdk 22. But nothing changes nothing.

**Comment by oliverou** [comment] 2016-11-28 05:08
I guess the issue is due to the DJI Go app run in the Android system background and grab the device connection. Please go to  "Settings->Apps->DJI GO->Force Stop" as shown below:

![screenshot_20161127-235604](https://cloud.githubusercontent.com/assets/13310805/20656838/a02e67e8-b56b-11e6-8541-853f4c18e035.png)

Make sure there is no other DJI related apps running in the background and try the demo again. It should works.

**Comment by lillogoal** [comment] 2016-11-28 08:55
Yes.  Although I had tried something similar. I noticed that the app (sample FPV DEMO), if I do not close the application forcefully at times when I open does not recognize the camera "Unknown aircraft". How can you fix this bug? (Then it is the same test that you did). But I did not understand how to solve app side. @oliverou THANK YOU

**Comment by oliverou** [comment] 2017-05-05 10:35
This issue has been resolved, close it now.

**Closed by oliverou** 2017-05-05 10:35 UTC
